/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AdminController;

/**
 *
 * @author Agnar
 */
public class AdminL extends javax.swing.JFrame {

    /**
     * Creates new form AdminL
     */
    public AdminL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelAname = new javax.swing.JLabel();
        LabelPassword = new javax.swing.JLabel();
        APwtf = new javax.swing.JPasswordField();
        AdminNameTF = new javax.swing.JTextField();
        ALoginBtn = new javax.swing.JButton();
        ACancelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NewULabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Adminpanel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFocusTraversalPolicyProvider(true);
        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 500));
        jPanel1.setLayout(null);

        LabelAname.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LabelAname.setText("Username:");
        jPanel1.add(LabelAname);
        LabelAname.setBounds(157, 173, 110, 30);

        LabelPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        LabelPassword.setText("Password:");
        jPanel1.add(LabelPassword);
        LabelPassword.setBounds(157, 223, 110, 28);
        jPanel1.add(APwtf);
        APwtf.setBounds(277, 225, 270, 28);

        AdminNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminNameTFActionPerformed(evt);
            }
        });
        jPanel1.add(AdminNameTF);
        AdminNameTF.setBounds(277, 175, 270, 30);

        ALoginBtn.setBackground(new java.awt.Color(0, 153, 153));
        ALoginBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ALoginBtn.setText("Login");
        ALoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALoginBtnActionPerformed(evt);
            }
        });
        ALoginBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ALoginBtnKeyPressed(evt);
            }
        });
        jPanel1.add(ALoginBtn);
        ALoginBtn.setBounds(275, 322, 100, 40);

        ACancelBtn.setBackground(new java.awt.Color(0, 153, 153));
        ACancelBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ACancelBtn.setText("Cancel");
        ACancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACancelBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ACancelBtn);
        ACancelBtn.setBounds(411, 322, 100, 40);

        jLabel1.setText("Forget Password ?");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(350, 270, 120, 14);

        NewULabel.setText("Create New Account");
        NewULabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewULabelMouseClicked(evt);
            }
        });
        jPanel1.add(NewULabel);
        NewULabel.setBounds(275, 392, 115, 22);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(393, 322, 0, 0);

        Adminpanel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Adminpanel.setText("Admin Login");
        jPanel1.add(Adminpanel);
        Adminpanel.setBounds(340, 80, 130, 60);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(447, 451, 111, 0);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\100.jpg")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 750, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminNameTFActionPerformed

    private void ALoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALoginBtnActionPerformed
        // TODO add your handling code here:
        AdminController.AdminL(AdminNameTF.getText(), APwtf.getText());
    }//GEN-LAST:event_ALoginBtnActionPerformed

    private void ALoginBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ALoginBtnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALoginBtnKeyPressed

    private void ACancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACancelBtnActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_ACancelBtnActionPerformed

    private void NewULabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewULabelMouseClicked

    }//GEN-LAST:event_NewULabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACancelBtn;
    private javax.swing.JButton ALoginBtn;
    private javax.swing.JPasswordField APwtf;
    private javax.swing.JTextField AdminNameTF;
    private javax.swing.JLabel Adminpanel;
    private javax.swing.JLabel LabelAname;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel NewULabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
